site_name: GORP Civilian Docs

nav:
  - Welcome: index.md
  - Rules and Regulations:
    - Rules: Rules/Rules.md
    - Changes: Rules/Change.md
    - Civilian Ranks:
      - Director / Deputy Director / Civilian Advisor: Rules/Rank/director.md
      - Civ Supervisor: Rules/Rank/supervisor.md
      - Senior Civilian: Rules/Rank/senior.md
      - Civ I: Rules/Rank/I.md
      - Civ II: Rules/Rank/II.md
      - Civ III: Rules/Rank/III.md
      - Civ IV: Rules/Rank/IV.md
      - Probationary CIV: Rules/Rank/Porb.md
    - Prioritys:
      - Prioritys: Rules/Prioritys/prioritys.md
      - Priority 3: Rules/Prioritys/priority-3.md
      - Priority 2: Rules/Prioritys/priority-2.md
      - Priority 1: Rules/Prioritys/priority-1.md
  - Important Information:
    - Fourms: Important/Fourms.md
    - Downloads: Important/Downloads.md
    - Crimiminal Code of Canada: Important/Code.md
    - In Game Commands:
      - Chat Commands: Important/Com/chat.md
      - Menus: Important/Com/MENU.md
      - CAD: Important/Com/CAD.md
    - Medical Calls:
      - Baseline: Important/Med/baseline.md
      - Allergic Reactions:
        - Food Allergy: Important/Med/React/food.md
        - Pet & Pollen Allergy: Important/Med/React/Pet.md
        - Drug Allergy: Important/Med/React/drug.md
      - Heat Stroke: Important/Med/heat.md
      - Seizure: Important/Med/seizure.md
      - Heart Attack: Important/Med/Heart.md
      - Stroke: Important/Med/Stroke.md
    - Calling 911: Important/911.md
    - Tow Trucks: Important/tow.md
    - Call Ideas: Important/call.md
  - Civilian Training:
    - Training: Trainging/Train.md
    - Testing: Trainging/Test.md
  - Meet The Team:
    - Department: Meet/Dept.md
    - Staff: Meet/Staff.md
  - FAQ:
    - Discord FAQ: FAQ/Discord.md
    - FiveM FAQ: FAQ/Fivem.md

theme:
  name: material
  favicon: favicon.ico
  logo: GORP.png
  features:
    - nevigation.tabs
    - navigation.sections
    - toc.intergrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.coede.copy
    - navigation.footer
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
      primary: red
      accent: red
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
      primary: blue
      accent: red


extra:
  social:
    - icon: fontawesome/brands/internet-explorer
      link: https://greaterontariorp.com/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/eZ7WWBZd6w
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/greaterontariorp/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@screw4darthvader?_t=8aXKcox8CwP&_r=1
  homepage: https://greater-ontario-gaming.github.io/CIVDocsGORP/Rules/Rules/

copyright:  |
  &copy; 2023 <a herf="https://github.com/deathstryder" target="_blank" rel="noopener">Greater Ontario Roleplay</a>
